// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(NotaCompraContext))]
    partial class NotaCompraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.NotaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEmissao");

                    b.Property<double>("ValorDesconto");

                    b.Property<double>("ValorFrete");

                    b.Property<double>("ValorMercadorias");

                    b.Property<double>("ValorTotal");

                    b.HasKey("Id");

                    b.ToTable("NotasCompra");
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<int>("Papel");

                    b.Property<string>("Senha");

                    b.Property<double>("ValorMaximo");

                    b.Property<double>("ValorMinimo");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "gerente",
                            Papel = 1,
                            Senha = "gerente",
                            ValorMaximo = 999999.98999999999,
                            ValorMinimo = 50000.010000000002
                        },
                        new
                        {
                            Id = 2,
                            Login = "subgerente",
                            Papel = 1,
                            Senha = "subgerente",
                            ValorMaximo = 999999.98999999999,
                            ValorMinimo = 1000.01
                        },
                        new
                        {
                            Id = 3,
                            Login = "vendedor",
                            Papel = 0,
                            Senha = "vendedor",
                            ValorMaximo = 999999.98999999999,
                            ValorMinimo = 10000.01
                        },
                        new
                        {
                            Id = 4,
                            Login = "auxiliar",
                            Papel = 0,
                            Senha = "auxiliar",
                            ValorMaximo = 999999.98999999999,
                            ValorMinimo = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
